branches:
  only:
    - master

install:
  - ps: |
      Install-PackageProvider -Name NuGet -Force | Out-Null
      Install-Module PsScriptAnalyzer -Force
      Install-Module -Name Pester -Force

environment:
  ModuleGItUrl: https://github.com/sbe-arg/Posh-Sumologic/archive/master.zip
  NuGetApiKey:
    secure: 9g0XGamfdzplyiYGs//sZteLfHaeciZve6EAYfIOqKWfgmS++0CFW9s8q7PdD+JA

build: false

test_script:
  - ps: $res = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($res.FailedCount -gt 0) { throw "$($res.FailedCount) tests failed."}

after_deploy:
  - ps: |
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/psget/psget/master/GetPsGet.ps1") | iex | Out-Null
      psget\Install-Module -ModuleUrl $env:ModuleGItUrl -Update
      try{ Publish-Module -Name Posh-Datadog -NuGetApiKey $env:NuGetApiKey }
      catch{ Write-Warning "Not publishing to PowerShellGallery. $($_.Exception.Message)" }
